# Generated by Django 4.1.5 on 2023-02-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='auto',
            field=models.CharField(default='Francis', max_length=50),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 2, 3)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
