# Generated by Django 4.1.5 on 2023-02-03 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0002_noticia_auto_noticia_fecha_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 16, 7, 59, 596595, tzinfo=datetime.timezone.utc)),
        ),
    ]
