# Generated by Django 4.1.5 on 2023-02-03 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0003_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 17, 5, 6, 14469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
