# Generated by Django 4.1.5 on 2023-02-03 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0004_alter_noticia_fecha_alter_noticia_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
