# Generated by Django 4.1.5 on 2023-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0005_alter_noticia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='auto',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='Francis', max_length=50),
        ),
    ]
