# Generated by Django 4.1.5 on 2023-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0006_remove_noticia_auto_noticia_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor_noticia',
            field=models.CharField(default='Francis', max_length=50),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pfp', models.ImageField(null=True, upload_to='upload')),
                ('edad', models.IntegerField()),
                ('autor_noticia', models.ManyToManyField(to='Noticias.noticia')),
            ],
        ),
    ]
