# Generated by Django 4.1.5 on 2023-02-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0008_remove_autor_autor_noticia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='autor_noticia',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor_noticia',
            field=models.ForeignKey(default='Anonimo', on_delete=django.db.models.deletion.CASCADE, to='Noticias.autor'),
        ),
    ]
