# Generated by Django 4.1.5 on 2023-02-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0009_remove_autor_autor_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor_noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noticias.autor'),
        ),
    ]
