# Generated by Django 4.1.5 on 2023-02-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0010_alter_autor_edad_alter_noticia_autor_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor_noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Noticias.autor'),
        ),
    ]
