# Generated by Django 4.1.5 on 2023-02-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0011_alter_noticia_autor_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(default='anonimo', on_delete=django.db.models.deletion.DO_NOTHING, to='Noticias.autor'),
            preserve_default=False,
        ),
    ]
