# Generated by Django 4.1.5 on 2023-02-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0014_alter_noticia_autor_delete_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
