# Generated by Django 4.1.5 on 2023-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0015_remove_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='francis', max_length=60),
        ),
    ]
