# Generated by Django 4.1.5 on 2023-02-07 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0018_noticia_img6'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='Noticias.autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
